name: Android Build & Upload APKs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew assembleDebug

      - name: Locate Debug APKs
        id: locate_apks
        run: |
          compatible_apk=$(find app/build/outputs/apk/compatible/debug -name "*.apk" | head -n 1)
          normal_apk=$(find app/build/outputs/apk/normal/debug -name "*.apk" | head -n 1)

          echo "compatible_apk=$compatible_apk" >> "$GITHUB_OUTPUT"
          echo "normal_apk=$normal_apk" >> "$GITHUB_OUTPUT"

      - name: Upload Compatible Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-compatible
          path: ${{ steps.locate_apks.outputs.compatible_apk }}
          if-no-files-found: error

      - name: Upload Normal Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-normal
          path: ${{ steps.locate_apks.outputs.normal_apk }}
          if-no-files-found: error
